# deprecated ...
version: '3'
services:
  postgres-container:
    image: postgres:15
    container_name: purl-db
    environment:
      POSTGRES_DB: purl
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    volumes:
      - ./postgres_orchestrator_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
